Get http://localhost:5173/v1/products
###
Get http://localhost:5173/v1/products/2
###
Post http://localhost:5173/v1/products
Content-Type: application/json

{
    "title": "Andra testprodukten via api anrop",
    "description": "fdfdf",
    "price": 42069,
    "imageUrl": "Ingen bild",
    "stock": 1000
}
###
Put http://localhost:5173/v1/products/1
###
Delete http://localhost:5173/v1/products/1
###